# Icons used for character connections
connection_icons = [
    "link",
    "favorite",
    "heart_broken",
    "sentiment_satisfied_outlined",
    "sentiment_dissatisfied_outlined",
    "handshake",
    "school",
    "work_outlined",
    "family_restroom_outlined",
    "people_outlined",
    "health_and_safety",
    "sports_esports",
    "link"
]

# Icons used in general purposes
icons = [
    "circle",
    "flag",
    "location_pin",
    "terrain",
    "forest",
    "water",
    "location_city",
    "stairs_outlined",
    "dangerous",
    "star",
    "flare", 
    "fireplace",
    "warning",
    "lightbulb",
    "help",
    "bookmark",
    "lock",
    "play_arrow",
    "pause",
    "send",
    "edit",
    "delete",
    "save",
    "cloud",
    "bug_report",
    "location_on",
    "home",
    "album",  
    "bolt", 
    "brightness_5",  
    "diamond", 
    "done", 
    "extension", 
    "favorite", 
    "group", 
    "villa",
]

